import "./globals.css";

export const metadata = {
  title: "LLP + AI Masters Project",
  description: "Generated by Binus Students",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
