import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "LLP + AI Masters Project",
  description: "Generated by Binus Students",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
